### ISSUE TITLE
Actividad 3- cuadro comparativo-sandrasalgadoperez-1BS

### ISSUE THREAD

**Issue by Sandrasalgado** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Sandrasalgado#2]
[actividad-3- cuadro comparativo -sandrasalgadoperez-1BS(2).pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Sandrasalgado/files/9481705/actividad-3-.cuadro.comparativo.-sandrasalgadoperez-1BS.2.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
14.1

**Comment by josealfredo79** [comment]
Es un cuadro comparativo...debe tener minimo 5 columnas...se debe volver hacer el trabajo...
