### ISSUE TITLE
Cuadro comparativo -Sandra Salgado Pérez -1BS

### ISSUE THREAD

**Issue by Sandrasalgado** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Sandrasalgado#3]
[cuadro comparativo- Sandra Salgado Pérez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Sandrasalgado/files/9523465/cuadro.comparativo-.Sandra.Salgado.Perez.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Le faltó elementos a comparar, le falto un acento, y tambien le falto justificar el texto, 16 de 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
